export { InstanceValidator } from "./validator.instance"
export { ChoiceValidator } from "./validator.choice"
export { DateValidator } from "./validator.date"
export { EmailValidator } from "./validator.email"
export { MaxValidator } from "./validator.max"
export { MaxLengthValidator } from "./validator.maxlength"
export { MinValidator } from "./validator.min"
export { MinLengthValidator } from "./validator.minlength"
export { NotAfterValidator } from "./validator.notafter"
export { NotBeforeValidator } from "./validator.notbefore"
export { PasswordValidator } from "./validator.password"
export { RegExpValidator } from "./validator.regexp"
export { RequiredValidator } from "./validator.required"
export { TypeValidator } from "./validator.type"
export { GenericValidator } from "./validator.generic"
export { IValidatorReport } from "./i.validator.report"
export { Validators, TValidatorName } from "./validators.validators"


export type TValidatorFunction = (value: any) => boolean
