import { Field } from '../fields/exports';
import { Report, SchemaReport } from '../reports/exports';
import { RequiredValidator } from '../validators/exports';


export interface SchemaDef {
	[key: string]: Field | Schema
}


export class Schema {
	schema: SchemaDef
	validators: [RequiredValidator] = [new RequiredValidator(true)]

	constructor(schemaDef: SchemaDef, requiredMessage?: string) {
		this.schema = schemaDef
		this.setRequired(requiredMessage)
	}

	private get toArray(): [string, Schema | Field][] {
		return Object.entries(this.schema)
	}

	get serialized() {
		return this.schema
	}

	get toJSON() {
		return JSON.stringify(this.serialized)
	}

	get requiredValidator(): RequiredValidator {
		return this.validators.find(validator => validator instanceof RequiredValidator) as RequiredValidator
	}

	get required(): boolean {
		return this.requiredValidator.required ?? false
	}

	static parse(j: { [key: string]: any }): Schema {
		try {
			let schemaDef: SchemaDef = {}
			Object.entries(j).forEach(([fieldname, _field]) => {
				if (_field.schema) {
					const field = (_field as Schema)
					const schema = Schema.parse(field.schema)
					const fieldRequired = field.validators[0]
					schema.setValidators([new RequiredValidator(fieldRequired.challenge, fieldRequired.message)])
					schemaDef[fieldname] = schema
				} else {
					schemaDef[fieldname] = Field.parse(_field)
				}
			});
			return new Schema(schemaDef)
		} catch (error) {
			throw new Error(`Cannot parsing schema : submited structure does not represent a valid string of schema definition. Please make sure that the definition submitted was generated by the Schema class\n${JSON.stringify(j)}`)
		}
	}

	static parseJsonString(j: string): Schema {
		return this.parse(JSON.parse(j))
	}

	setRequired(message?: string) {
		this.validators = [new RequiredValidator(true, message)]
		return this
	}

	setValidators(validators: [RequiredValidator]) {
		this.validators = validators
		return this
	}

	validate(data?: { [key: string]: any }): boolean {
		if (data) {
			return this.toArray.every(([fieldname, field]) => field.validate(data[fieldname]) ?? false)
		} else if (this.required) {
			return false
		} else {
			return true
		}
	}

	report(data?: any): SchemaReport | Report[] {
		if (data) {
			let report: SchemaReport = {}
			this.toArray.forEach(
				([fieldname, field]) => {
					report[fieldname] = field.report(data[fieldname])
				})
			return report
		} else {
			return [this.requiredValidator.report(data)]
		}
	}
}
